-- 코드를 입력하세요
SELECT a.PRODUCT_CODE, (a.PRICE * b.AMOUNT) AS SALES
FROM PRODUCT a
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) b
    ON a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY SALES DESC, a.PRODUCT_CODE;