-- 코드를 입력하세요
SELECT b.MEMBER_NAME, a.REVIEW_TEXT, DATE_FORMAT(a.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW a
JOIN MEMBER_PROFILE b
    ON a.MEMBER_ID = b.MEMBER_ID
WHERE b.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1)
ORDER BY REVIEW_DATE, a.REVIEW_TEXT;